### ISSUE TITLE
Plugin not working correctly with aliases (select, join, orderBy)

### ISSUE THREAD

**Issue by CristianSitov** [ekvedaras/laravel-query-intellij#81]
If having a model `Profile` like:

```php
<?php

namespace App\Models;

use App\Model;
use Eloquent;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * @package App\Models
 * @mixin Eloquent
 */
class City extends Model
{
    public function state(): BelongsTo
    {
        return $this->belongsTo(State::class);
    }
}
```

Then highlighting would look like the screenshot below:

<img width="842" alt="CleanShot 2022-02-22 at 13 22 38@2x" src="https://user-images.githubusercontent.com/1521586/155122632-312ad1c5-42a0-4893-b2f7-d096243ea697.png">

**Comment by ekvedaras** [comment]
Thank you, will try to reproduce 🙂

**Comment by ekvedaras** [comment]
Ok I think the issue is with `AS` instead of `as`. Not sure how I missed that case 😀 Will add support for `AS` 🙂

**Comment by ekvedaras** [comment]
Fixed autocomplete, but something is still off with inspection. Will take a look again 🙂

**Comment by ekvedaras** [comment]
Fixed in `v3.0.3`

**Comment by RobinBastiaan** [comment]
I still have the problem when using a raw DB statement. See the example code below where the column "date" is not found as the parameter of `orderBy`.

Example code:
```
City::query()
->select([DB::raw('DISTINCT(DATE(IFNULL(cities.start, cities.end))) as date')])
->orderBy('date');
```

Should I make a new issue for this? Thank you very much for your time and your plugin.
